### ISSUE TITLE
Calling $(selector).minicolors('value','#00000') returns undefined error

### ISSUE THREAD

**Issue by CNovakCAA** [claviska/jquery-minicolors#117]
Using the most up-to-date version of color picker (2014-01-14) creates an error when calling:

$('.color').minicolors('value','#00000');

If the .color selector has previously been inited as a minicolor element.

The error is:

"Cannot read property 'letterCase' of undefined"

On line #480, the settings variable is undefined on subsequent calls to the plugin. It appears your "public" methods don't maintain their scope (or a reference to the plugin itself) and have no idea what "settings" are.

However, even if I hack in something like this:

var settings = $.minicolors.defaultSettings;

The undefined errors are resolved, but the click event handler of your plugin no longer does anything. That means manually updating the color through your own "value" method disables your plugin.

**Comment by NiltonMoraesNeto** [comment]
Help Me!!!! Please!

C# net Core 3.1

![image](https://user-images.githubusercontent.com/11524838/79081116-c3f79780-7cf0-11ea-8569-e8ee52d62fd7.png)

**Comment by harikrishna-trivedi** [comment]
$("#ElementID").minicolors({
                control: $(this).attr('data-control') || 'hue',
                defaultValue: $(this).attr('data-defaultValue') || '',
                format: $(this).attr('data-format') || 'hex',
                keywords: $(this).attr('data-keywords') || '',
                inline: $(this).attr('data-inline') === 'true',
                letterCase: $(this).attr('data-letterCase') || 'lowercase',
                opacity: $(this).attr('data-opacity'),
                position: $(this).attr('data-position') || 'bottom left',
                swatches: $(this).attr('data-swatches') ? $(this).attr('data-swatches').split('|') : [],
                change: function (hex, opacity) {
                },
                theme: 'bootstrap'
            });

Before above code of init minicolors, If you change value, this error will defiantly occurs.
