### ISSUE TITLE
Support for IE8

### ISSUE THREAD

**Issue by lukyrys** [claviska/jquery-minicolors#124]
Change event.pageX/Y to event.clientX/Y only for IE 8

```
    var input = target.parents('.minicolors').find('.minicolors-input'),
        settings = input.data('minicolors-settings'),
        picker = target.find('[class$=-picker]'),
        offsetX = target.offset().left,
        offsetY = target.offset().top,
        //x = Math.round(event.pageX - offsetX),
        //y = Math.round(event.pageY - offsetY),
        x = Math.round(
                            (($.browser.msie  && parseInt($.browser.version, 10) === 8) ? event.clientX : event.pageX)
                            - 
                            offsetX
                    ),
        y = Math.round(
                            (($.browser.msie  && parseInt($.browser.version, 10) === 8) ? event.clientY : event.pageY)
                            - 
                            offsetY
                    ),
        duration = animate ? settings.animationSpeed : 0,
        wx, wy, r, phi;
```

**Comment by madhukarhere** [comment]
Gradient is not working in IE8. Rest is all fine. Also it is picking up the gradient colors it is just displaying the gradient.

**Comment by claviska** [comment]
For IE7/8 support, set `dataUris` to `false` per the [settings page](http://labs.abeautifulsite.dev/jquery-minicolors/#settings).

**Comment by madhukarhere** [comment]
Unable to open this settings page. http://labs.abeautifulsite.dev/jquery-minicolors/#settings.
which style I need to override for this.

**Comment by claviska** [comment]
Sorry. Change it to .net.

**Comment by madhukarhere** [comment]
No luck. Still gradient is not loading in IE8. Even the colour pickers in the demo site are also not working.
http://labs.abeautifulsite.net/jquery-minicolors/#demos is not working.

**Comment by markvantilburg** [comment]
The demo page is not ie8 compatible since it uses the datauris

**Comment by madhukarhere** [comment]
Thanks for the reply. Any clue to make it work in IE 8.

**Comment by markvantilburg** [comment]
Please show the code how you initialize it.

**Comment by madhukarhere** [comment]
$('.minicolors').minicolors({ theme: 'defaultUpdate', dataUris: false, letterCase: 'uppercase' });

**Comment by markvantilburg** [comment]
Where did you put the .png file? The default is in the same folder as the .css file

**Comment by madhukarhere** [comment]
Thank you very much for the help. It is working now. Our version of minicolors is old. It is working after upgradation. :+1:
