### ISSUE TITLE
Feature request - No color/nothing selected

### ISSUE THREAD

**Issue by riaan53** [claviska/jquery-minicolors#155]
Hi,

I need to select multiple objects and each can have its own color. If the color is the same then its fine I just set minicolors to that color. But if the color is different I need to have something like 100% opacity with a cross in it to show that no color is selected. And when you click on it minicolors open as normal with nothing selected and you can choose a color as normal.

Can you point me in the right direction please?

Thank you.

Regards,
Riaan

**Comment by claviska** [comment]
This is actually possible by using the `keywords` option and setting the value to `transparent`. If desired, you could also enable swatches as well.
