### ISSUE TITLE
Documentation - dataUris disable for IE8

### ISSUE THREAD

**Issue by markvantilburg** [claviska/jquery-minicolors#157]
dataUris

    Set this to false if you require IE7 support. This setting will force the plugin to load an external image instead of using dataURIs.

    Set this to false if you require IE7 or IE8 support. This setting will force the plugin to load an external image instead of using dataURIs.

The current image in the data uri seems to be to big for IE8 to render..

http://blogs.msdn.com/b/ieinternals/archive/2010/09/15/ie9-beta-minor-change-list.aspx
"The DataURI length limit was raised from 32kb to 4gb; longer DataURIs are important for some scenarios, particularly for the Canvas element's toDataURL() method. However, the IE9 Beta has a known bug where DataURIs that exceed 4kb are not permitted for FONT-FACE rules in CSS. "

**Comment by markvantilburg** [comment]
Maybe also add that for mobile browsers it would be better to disable data uri's as loading them is much slower.

**Comment by claviska** [comment]
Yep, that's a typo. The docs should have said IE7 or IE8. Will fix.
