### ISSUE TITLE
Making the popup wheel larger

### ISSUE THREAD

**Issue by tridentNestea** [claviska/jquery-minicolors#160]
Hi, how would I go about increasing the size of the popup color wheel?

**Comment by claviska** [comment]
You'd have to generate a larger image (so it won't be blurry), update the CSS, and then also update the math functions. (It's a bit of work since the plugin wasn't designed to be resized.)

**Comment by tridentNestea** [comment]
Ok thanks for the help, I'll look into that. This plugin is exactly what I need otherwise, great work!
