### ISSUE TITLE
class="minicolors" removes $_POST

### ISSUE THREAD

**Issue by svrabl** [claviska/jquery-minicolors#161]
with mutliple colorpickers on same page, the name="COLOR_$i" is not in the $_POST after submitting form.

As soon as I remove class="minicolors" POST works fine.

**Comment by claviska** [comment]
This works fine in the demo if you add `name` attributes to the inputs—the plugin doesn't change the name or ID, only the value, so I can't see how it would fail.

Please post a minimal test case so I can look into this.

**Comment by svrabl** [comment]
I wrote a minimal test page. It worked fine!

The problem was on my page. I opened a div before the form, which I closed inside the form. Somehow it only affected the $_POST part associated with minicolors. 

Thanks, great colorpicker!
