### ISSUE TITLE
Doesn't select color

### ISSUE THREAD

**Issue by etcook** [claviska/jquery-minicolors#162]
I'm running into a situation where jquery-minicolors where if it's present with another input field, it doesn't want to select the color and instead just follows the mouse until you hit escape. By itself, it's ok.

I'm using it within an angular link, instantiating it on the $element itself.

Wondering if you had some ideas on how to troubleshoot. Unfortunately the app is a bit big to recreate in a plunkr. Any guidance would be highly appreciated. Thanks!

**Comment by claviska** [comment]
I'm not familiar with Angular, but if you can strip it down somehow to a minimal test case I'll be glad to take a look. From the description, I have no idea what might be happening.

**Comment by etcook** [comment]
@claviska May I have your email? I can send you an internal link.

**Comment by claviska** [comment]
Have you tried looking to see if the miniColors input is being modified in any way? Or if any of the generated miniColors code is being changed? (The plugin wraps the input with a <div> and adds some other elements that could be getting in the way of something else you have going on the page.)

Can you disable other plugins/functionality one-by-one to help narrow it down? It could be simply a conflict with another script or plugin.

I haven't heard of anyone having troubles using this with Angular, but then again I haven't really come across anyone using them together either (although I'm sure there have been). I'd love to help, but I'd prefer to not go poking around in someone else's app :)

**Comment by etcook** [comment]
I've compared the markup between the one that works and the one that doesn't, and they're identical. I'm not using any other plugins.

**Comment by claviska** [comment]
Hmm, I would try to strip the affected page down as much as possible...remove piece by piece until it starts working and hopefully that will help identify what's causing it.

**Comment by claviska** [comment]
I'm convinced this is an implementation issue. I'll be happy to look at it if you can provide a fiddle, otherwise we're just speculating.
