### ISSUE TITLE
How to enable rgbObject ?

### ISSUE THREAD

**Issue by MarieComet** [claviska/jquery-minicolors#163]
Hi, i'm trying to return the rgb value of the current color selected:
```
      $('input.minicolors').minicolors({
        control: 'wheel',
        inline: true,
        change: function(rgbObject) {
        console.log(rgbObject);
        }
      });
```
but console.log return : #61ff73, not rgb object.
Anyone can show me a simple example of rgbObject method usage ?

Thanks

**Comment by claviska** [comment]
You're accessing the argument, which is always the hex color. Use the method instead:




rgba = $('.selector').minicolors('rgba'); // or rgb






— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net

**Comment by MarieComet** [comment]
```
$('input.minicolors').minicolors({
        control: 'wheel',
        inline: true,
        change: function(rgb) {
        var rgb = $('input.minicolors').minicolors('rgb');
        console.log(rgb);
        }
      });
```
Thanks, but this method return:
```
[input.minicolors.minicolors-input, selector: "input.minicolors", context: document, jquery: "1.11.2", constructor: function, toArray: function…]
```
not the rgb

**Comment by claviska** [comment]
Method was off the top of my head. Look at the demo/docs. It's rgbObject or rbgString/rgbaString.






— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net

**Comment by MarieComet** [comment]
Thanks but I have look the docs. It doesn't help me anymore.

**Comment by MarieComet** [comment]
So, it's working fine like this : 
```
$('input.minicolors').minicolors({
        control: 'wheel',
        inline: true,
        change: function(rgbString) {
        var rgb = $('input.minicolors').minicolors('rgbString');
        console.log(rgb);
        }
      });
```
Thanks ;)
