### ISSUE TITLE
Pass through to original input events

### ISSUE THREAD

**Issue by tabfugnic** [claviska/jquery-minicolors#165]
Using this plugin and trying to create an event that passes through to the event originally set on the object. If I create a unique event, such as "forceChange", and trigger that explicitly, it doesn't appear to be hitting that. Any suggestions or thoughts on what I'm doing wrong?

**Comment by claviska** [comment]
Are you listening and creating it on the input element itself? Might need to see code.






— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net

**Comment by claviska** [comment]
Closing due to no response. If this is still an issue, provide more info and I'll reopen.
