### ISSUE TITLE
How to make .minicolors-slider-wheel horizontal instead of vertical?

### ISSUE THREAD

**Issue by Spoowy** [claviska/jquery-minicolors#166]
Hey guys,
what's the best way of making this: https://s3.amazonaws.com/f.cl.ly/items/1f0q3m24441W2c1y091G/Screen%20Shot%202015-06-12%20at%2015.54.30.png

to this: https://s3.amazonaws.com/f.cl.ly/items/2O3p0g0o2319101U0i20/Screen%20Shot%202015-06-12%20at%2015.55.06.png

I rotated it via css with...
    -webkit-transform: rotate(90deg);
    -moz-transform: rotate(90deg);
    -o-transform: rotate(90deg);
    -ms-transform: rotate(90deg);
but after that the slider won't work anymore.

Many thanks!

**Comment by Spoowy** [comment]
Ok superstars,
here you go: https://jsfiddle.net/y130qjp8/

It's a dirty messy way but yep. Does it well.

**Comment by claviska** [comment]
Careful, the slider no longer works on touch devices.



On Friday, Jun 12, 2015 at 10:34 AM, Spoowy <notifications@github.com>, wrote:

Closed #166.

**Comment by Spoowy** [comment]
The minicolors itself or is it just my adjusted version? @claviska

**Comment by claviska** [comment]
Just the modified version.







On Friday, Jun 12, 2015 at 11:30 AM, Spoowy <notifications@github.com>, wrote:

The minicolors itself or is it just my adjusted version? @claviska

**Comment by Spoowy** [comment]
Ok, great!

Will update the jsFiddle when I’ve fixed this.

**Comment by Spoowy** [comment]
Updated.

It works now on touch as well.
