### ISSUE TITLE
console.log is in source

### ISSUE THREAD

**Issue by onassar** [claviska/jquery-minicolors#172]
Heya -
Thanks for all you work; just wondering why this is in the source:
https://github.com/claviska/jquery-minicolors/blob/master/jquery.minicolors.js#L733

**Comment by markvantilburg** [comment]
introduced in ed30f47330cb50ccd92e40f284e7e3b32e62726d

Changed in pull 173

**Comment by onassar** [comment]
damn you're fast ;)
