### ISSUE TITLE
Duplicates call being made for single action (feature request)

### ISSUE THREAD

**Issue by onassar** [claviska/jquery-minicolors#174]
Thanks for all your work with this. Really great
I'm finding myself in a situation where within the UI, I access a hex and opacity value
I want the input to only show the hex, so I'm making two calls as follows (when the user selects their hex/opacity):

    $input.minicolors('value', hex);
    $input.minicolors('opacity', opacity);

The result of doing this is the `change` function/callback bound to the object is fired twice. I totally understand why this is, but it's causing a few irregularities in my specific use case.

Is there any way for me to pass in an object defining the values for the minicolors picker? The key being that it only triggers the `change` function/callback one.

Perhaps something like:

    $input.minicolors('value', {
        color: 'hex',
        opacity: 0.5,
    });

It would allow myself (and I'm sure others) a bit more flexibility for how the library interacts with our codebases, while maintaining the consistency of your library.

Thanks for your help!

**Comment by claviska** [comment]
Good idea. I'll see what I can do.

**Comment by onassar** [comment]
Awesome thanks @claviska

**Comment by claviska** [comment]
Fixed in https://github.com/claviska/jquery-minicolors/commit/c3d57f4de327be371337512da6a04dd8a989373d.
