### ISSUE TITLE
Bugs in RGB(A) support

### ISSUE THREAD

**Issue by claviska** [claviska/jquery-minicolors#175]
Almost ready to release RGB(A) support. Here's what's left for bugs that we know of:

From #170:

> Also, after you posted this I played around with the first RGB(A) example in the demo and realized that you can enter an RGBA value [for example: rgba(50, 100, 150, .5)] and the RGBA format will "stick" while dragging, but revert to RGB on blur. This is a bug. The control should always display an RGB string since opacity is disabled.

I'll get to it as soon as I can, but consider it open to anyone who cares to work on it :)

/cc @JoomliC

**Comment by JoomliC** [comment]
Hi @claviska , i was busy too this week, and away a part of it ;-) (days are too short!)
Maybe not tomorrow, but for sure some time on Tuesday.

I will keep you in touch!
Cheers!
Cyril

**Comment by harisrozak** [comment]
I have found some workaround for the bugs.
I changed some code (line 358):
```
format = input.attr('data-format'),
keywords = input.attr('data-keywords'),
```
To:
```
format = input.data('minicolorsSettings').format,
keywords = input.data('minicolorsSettings').keywords,
```

And change some script on `function parseRgb(string, obj)` to enable opacity 0 :
```
if( rgba[3] ) {
    return 'rgba(' + rgba[0] + ', ' + rgba[1] + ', ' + rgba[2] + ', ' + rgba[3] + ')';
} else {
    return 'rgb(' + rgba[0] + ', ' + rgba[1] + ', ' + rgba[2] + ')';
}
```
To:
```
if(typeof(rgba[3]) !== 'undefined' && rgba[3] < 1) {
    return 'rgba(' + rgba[0] + ', ' + rgba[1] + ', ' + rgba[2] + ', ' + rgba[3] + ')';
} else {
    return 'rgb(' + rgba[0] + ', ' + rgba[1] + ', ' + rgba[2] + ')';
}
```

**Comment by JoomliC** [comment]
Hello,

Was to busy this week to have a look, but will be easier now to check this and help to fix!

Thanks @harisrozak for your help!
What is supposed to change with this : 
```
format = input.data('minicolorsSettings').format,
keywords = input.data('minicolorsSettings').keywords,
```
(sorry, notice no difference...)

```
if(typeof(rgba[3]) !== 'undefined' && rgba[3] < 1) {
    return 'rgba(' + rgba[0] + ', ' + rgba[1] + ', ' + rgba[2] + ', ' + rgba[3] + ')';
} else {
    return 'rgb(' + rgba[0] + ', ' + rgba[1] + ', ' + rgba[2] + ')';
}
```
I agree with this! :+1: 
I would have change too (and not only there) the <code><1</code> by <code><=1</code> to keep a rgba string, with alpha to 1 ;-)

So, i'm still checking the issue reported here, as i think your changes are not fixing what @claviska reported... If i have understood well, when entering a rgba value inside the input, it should not update the control if opacity is disabled, and it should then return an empty input value on blur.
And if opacity is enabled, when entering a rgb value, it should not update the control, and return a blank input on blur.
Do i'm right in my understanding @claviska ?

**Comment by claviska** [comment]
Correct. In short, the control should always display RGB if opacity is disabled and RGBA if opacity is enabled.

**Comment by JoomliC** [comment]
PR created : https://github.com/claviska/jquery-minicolors/pull/176

;-)
