### ISSUE TITLE
White always selected at load

### ISSUE THREAD

**Issue by dotmartin** [claviska/jquery-minicolors#178]
When initialising the library on an input field with value set to a valid colour it gets handled by the plugin and the correct color is shown on the swatch, however when opening the picker the handle sits at the top left corner and hue slider on top, so when the user drags the colour is set to white, and the hue is always red. 

I'm thinking it might be an issue with the position or display attributes of our input field, are there any things to consider when placing them?

<img width="312" alt="After init" src="https://cloud.githubusercontent.com/assets/1218027/10488444/f5ab4d38-7298-11e5-8db6-26d4c7611e65.png">

<img width="307" alt="After dragging a little" src="https://cloud.githubusercontent.com/assets/1218027/10488451/fe91389a-7298-11e5-9c3e-4aaffd974efe.png">

**Comment by claviska** [comment]
I don't know of any positioning that would cause this. I'd suggest slowly stripping it down to see what might be affecting it. 

I double-checked both demos just to be sure and neither experience this behavior. Would love to identify the cause and your solution to it :)

**Comment by dotmartin** [comment]
Yeah I know. I just cannot figure out what I am doing wrong. This isn't to be considered a bug, I just wanted your take on it. 

I have to set the value of the input field using jQuery and then initiate the colorpicker, have tried both $input.val('#33ff00'); and $input.attr('value', '#33ff00'); both produce the same results.

**Comment by claviska** [comment]
Have you tried:

$input.minicolors('value', '#33ff00');

Also, the control will pick up existing values:

<input ... value="#33ff00">

If you're setting with JS after initializing, always use the API.

Aside from that, there could be a conflict elsewhere in your script. Try commenting out everything else except the color picker init. If the problem persists, could be a bug. If not, I comment things little by little to identify what's conflicting.

Hope that helps.

**Comment by dotmartin** [comment]
Thanks Cory, I'll keep you posted on my progress!

**Comment by dotmartin** [comment]
I have tried just about everything now, it always does the same thing to me. Since I do not have the value at load time I need to fill it in later, and it just does not seem to pick it up. I commented out things like updating my swatch and other event handling.

The hue selector gets the correct color range, as can be seen in my screenshots above, but the handles does not, and when you drag the handle it flips back to the red spectrum. 

I can use $input.minicolors('value') to get the value, and I managed to use the console and set the color manually when everything was loaded using $input.minicolors('value', '#beef01'), and then everything worked as expected. 

Please let me know if you'd want me to try something else!

**Comment by claviska** [comment]
Not sure without seeing actual code. Are you able to setup a fiddle that demonstrates the behavior?

**Comment by dotmartin** [comment]
I have tried to replicate our behaviour in a fiddle, but I cannot get it to fail, It must be somewhere on our side. I'll close the issue for now and get back to you if I find something out. 

Thanks for your help so far, much appreciated!
