### ISSUE TITLE
Support for use strict

### ISSUE THREAD

**Issue by IDontEatSoap** [claviska/jquery-minicolors#179]
The script currently fails if minified inside a package with "use strict".

Errors such as "$input_size is not defined" show up.

As best practice, should we update it to be complaint with "use strict"?

**Comment by claviska** [comment]
Yes we should, although the real best practice here is to only use "use strict"; inside of a closure so it won't affect other libraries when compiled.

That said, I'll leave this open as a feature request until I can get to it (open to PRs—shouldn't take too much). However, I'd suggest contacting the authors of the other library to make sure they're aware of the issue so they can fix it as well.

**Comment by IDontEatSoap** [comment]
Some minifiers like uglify add "use strict" straight at the top - so we can't really wrap it around a scope... :(

**Comment by claviska** [comment]
Wasn't aware that uglify did that. I'm using it through CodeKit and never ran into any issues with it. Weird.

**Comment by claviska** [comment]
I fixed a few issues and added `use strict`. I haven't noticed any other issues yet, but testing is welcome.
