### ISSUE TITLE
Can't init colorpicker on dynamic created input

### ISSUE THREAD

**Issue by Ramonlord** [claviska/jquery-minicolors#181]
**Step to reproduce**
```javascript
var inpt = jQuery('<input>');
inpt.minicolors({});
jQuery('body').append(inpt);
```
Seems like problem is in jQuery `.before()` and `.after()` methods, they doesn't work with dynamic created elements

**Comment by claviska** [comment]
Try this:

```javascript
var inpt = jQuery('<input>');
jQuery('body').append('inpt');
inpt.minicolors({});
```

**Comment by Ramonlord** [comment]
Yes, but in my situation i can't init plugin after i add it to the page. I try fix places which i found, but seems like need to go deeper.
Thanks for the help
