### ISSUE TITLE
Possible to change minicolors value (color/opacity) without triggering change event?

### ISSUE THREAD

**Issue by onassar** [claviska/jquery-minicolors#183]
Thanks for your help earlier @claviska -
Within my app, I'd like to set the color/opacity of a minicolors-powered input, but not have it fire the `change` event. Rather, I'd only like the `change` event to fire when the user interacts with the widget. Is this possible?

**Comment by onassar** [comment]
For now, I'm running the following to prevent a call to `change`

    $input.data('minicolors-initialized', true);

**Comment by claviska** [comment]
You could set a variable before you programmatically change it and then unset it right after:

var myVar = false;

// To set value programmatically
myVar = true;
$('input').minicolors('value', '...');
myVar = false:

// To watch for changed
$('input').on('change', function() {

    if( myVar ) return;

    ...

});

I would advise against altering the control's data as it the data could be altered or may even change in a future release. It also may not work 100% how you expect. It's always better to use the official API :)

**Comment by onassar** [comment]
Great thanks @claviska. I'll give the more direct route a go (variable checking within `change` event function).
