### ISSUE TITLE
When selecting a color in the picker, color resets to #ffffff

### ISSUE THREAD

**Issue by StephaneBischoff** [claviska/jquery-minicolors#184]
Hi, 

Thanks for this great control !

I have an issue where if the user selects a color in the right side of the picker (color palette), the initial color is reverted to white (#ffffff) even if I set the initial value to something else. I tried setting the default value, but the issue is still there. The issue seems to be that the dropdown picker does not set the initial color correctly. instead, its always set to white (top left corner of the picker)

Here is the basic flow.

1. I show the color picker with an initial color (red for example)
2. The minicolors control is shown. The input has the proper red value shown.
3. User selects the control, the dropdown color picker is shown.
4. User clicks in the color palette picker (on the right) to change the color palette. 
5. The red color is change to white. (issue here. I would like the starting color to be the proper red. Seems like the dropdown color is always set to white... top left corner.)

Here is what I got;

```
 var $input = $j("input", $colorInput);
 $input.minicolors({
     control: $j(this).attr("data-control") || "hue",
     defaultValue: property.value,
     format: $j(this).attr("data-format") || "hex",
     inline: $j(this).attr("data-inline") === "true",
     letterCase: $j(this).attr("data-letterCase") || "lowercase",
     position: $j(this).attr("data-position") || "bottom left",
     change: function (hex) {
           this.saveColor(hex);
     }.bind(this),
     theme: "default"
});
$input.attr("value", property.value);
```

Thanks

**Comment by StephaneBischoff** [comment]
If I tab into the input control, this issue is resolved. The color is correctly chosen in dropdown. But, if I use the mouse to click into it, then the issue exists as mention above.

**Comment by claviska** [comment]
Hi, I'm having a hard time reproducing this. Can you post a minimal fiddle to demonstrate the issue? This will also help ensure the issue isn't with conflicting code.

Thanks :)

**Comment by claviska** [comment]
Closing due to no response. If this is still an issue for you, please submit a minimal test case so I can look into it.

**Comment by JoeGarcia2** [comment]
I'm actually struggling with this. It's happening when I set the window zoom like so:
var zoomB = `${1.5 / window.devicePixelRatio * 100}%`;
document.querySelector('body').style.zoom = zoomB;

I need to set the zoom on the Mac as it doesn't scale the interface correctly.
