### ISSUE TITLE
Custom trigger after the input is updated?

### ISSUE THREAD

**Issue by curagea** [claviska/jquery-minicolors#190]
Hello there,

I'm currently using MiniColors along with Backbone, and I need to be able to save the color value to a Backbone Model upon 'blur' on the corresponding input. The input itself is in a Backbone View with a 'blur' event attached to it, to do the saving.

I found out that, at least in my case, 'blur' events on the Backbone View happen before the 'blur' event for MiniColors. This isn't an issue for values chosen from the color swatch, but for values directly keyed in, the Backbone View ends up fetching the raw, pre-parsed value.

Would it be possible to have a trigger, such as "afterChange" or "afterUpdate", trigger at the end of `updateInput()` in the source code? This would help me immensely, as I can then listen to that trigger instead of 'blur' and fetch the properly parsed value.

**Comment by claviska** [comment]
MiniColors has a `change` callback that you can watch for. This will always present the most accurate value for the control.

It does fire quite a bit as you drag over the color palette, but that can be offset using the `changeDelay` setting. [Details here](http://labs.abeautifulsite.net/jquery-minicolors/)

At this time, there's no blur event in the API, which means it could vary depending on browser :)

**Comment by curagea** [comment]
Hmm, I noticed the `change` callback is called on `keyup` events, for values that are typed in. The `blur` event doesn't trigger the callback.

There were some other Backbone events colliding with the events that MiniColors is listening. I managed to fix things up, but ideally having a `blur` callback or the aforementioned custom trigger would be nice. I think it would be less resource-intensive to fetch values on `blur` rather than `change`, the latter which fires on every `keyup`, and `changeDelay` doesn't help much if the user is a slow typer :)

Hope that clarified things.

**Comment by claviska** [comment]
Have you considered using the `hide` event? Unless you're using an inline control, this will be called when a selection is made and the color picker is hidden.

**Comment by claviska** [comment]
We don't fire change on blur because by that time, the change event has already been triggered by dragging/typing/etc. and change won't fire twice with the same value.

> ideally having a blur callback or the aforementioned custom trigger would be nice. I think it would be less resource-intensive to fetch values on blur rather than change, the latter which fires on every keyup, and changeDelay doesn't help much if the user is a slow typer :)

Change is only called when a valid 3 or 6-character hex color is entered. No matter how slow you type, entering `#-F-F-0-0-0-0` will only fire the change event twice. The `changeDelay` option is intended to debounce dragging and has practically no affect on typing.

Closing this since there are no plans to expose blur/focus events.
