### ISSUE TITLE
add context option

### ISSUE THREAD

**Issue by Sysix** [claviska/jquery-minicolors#192]
hey guys,

very nice plugin :) thanks for it.
I have a little problem: If I use the plugin in a container with overflow:hidden the minicolors-container is isolated.

Maybe add a Option like Bootstrap "context" so we can add this on the body-tag or somewhere else.

Greez Sysix

**Comment by andreasfernandez** [comment]
We have a similar use-case where a modal is generated within a frame and and then displayed in top.document. The events of the color picker listen to document, which is the frame. We could bypass this by changing the event selector to `$([document, top.document])`, but I'm not sure if this change has some side-effects.

**Comment by claviska** [comment]
Resolved in #207.
