### ISSUE TITLE
swatch doesn't look good when using input-sm with bootstrap theme

### ISSUE THREAD

**Issue by ale1981** [claviska/jquery-minicolors#193]
As title, the swatch span looks too big for the input, no margin at the bottom? 
Is there any CSS I can change to alter this?

**Comment by ale1981** [comment]
If I override the CSS and change the height and width of the minicolors-swatch to 24px then it looks better. I am guessing you don't check for the input sizes with bootstrap, I might be wrong?

**Comment by claviska** [comment]
Correct. To properly support all input variations in Bootstrap we'd need to provide a Less version (and a Sass version for BS4). The `bootstrap` theme is intended to be a starting point, so customizing it may be necessary even if you've simply change the base font size in Bootstrap.
