### ISSUE TITLE
Feature Request: Use HEX Colour if Opacity = 1

### ISSUE THREAD

**Issue by JD-Robbs** [claviska/jquery-minicolors#195]
It would be great to be able to use minicolors in `hex` mode in conjunction with "transparency: true" and only return an `rgb(a)` value if the transparency is not `1`.

Basically:
- rgba(0, 0, 0, 1) --> #000000 
- rgba(0, 0, 0, 0.5) --> rgba(0, 0, 0, 0.5)

I've tried to get this working with the current version by grabbing the color/transparency values in the `change` event and then overriding my input's value with the hex colour if there's no transparency (i.e. `1`).  
However, upon closing, the hex value gets overridden again by the rgba value.  I also tried doing the same in the `close` event (since that's where it got overridden) - unfortunately no luck, since it gets re-converted once the widget opens again.

Anyway, just wondered if this would be a useful addition or, in fact, it is already possible with the current version?

**Comment by claviska** [comment]
I'm not sure if changing the format on the fly is a good idea. I think it would confuse users. Open to hearing other thoughts on this.

**Comment by JD-Robbs** [comment]
Yes, you're absolutely right - definitely not as a default.  I was thinking more along the lines of an additional format such as `format: composite`.  One thing I also tried is setting the new format option in the `change` event; but it closes and re-renders the widget.  All this being said, I'm aware this may be quite an edge case scenario with little demand - just putting it out there. :smiley:

**Comment by claviska** [comment]
Closing since the complexity of code to support this use case far outweighs its demand. You can also make those conversions using the given values :)
