### ISSUE TITLE
NPM version of this repo is not up to date

### ISSUE THREAD

**Issue by samjarrett** [claviska/jquery-minicolors#198]
Hi, I was migrating from bower to npm for this dependency, and realised that the various tags for this repo aren't synced with the npm registry (latest that NPM has is 2.1.10): https://www.npmjs.com/package/jquery-minicolors

**Comment by claviska** [comment]
Somebody else published it to NPM so I guess it doesn't update automatically :-\

**Comment by claviska** [comment]
The official NPM repo is namespaced and can be installed via:

```
npm install --save @claviska/jquery-minicolors
```
