### ISSUE TITLE
RE: Bug when selecting Opacity 0

### ISSUE THREAD

**Issue by devcon7** [claviska/jquery-minicolors#201]
Hello,

I am using multiple settings with the same class name to select color with opacity for many fields from the same page.

First of all, it works fine, but I found a bug when you select Opacity to 0 using the color picker then click outside of the color picker box, it goes to rgb(x,x,x) instead of rgba(x,x,x,0). 

Also, when I am selecting '1' as the opacity value, while I have the color picker open, the input field shows rbg(x,x,x) instead of rbga(x,x,x,1), but when I click out side of the color picker, it changes to rbga(x,x,x,1).

What's really interesting is if i select the opacity to non-zero like 0.1, it works fine. i.e. rgba(x,x,x,0.1).

I also realized that when I use "inline," I don't have any of these problem.

What's going on?

Here is the setting I use:

```javascript
$('.my-class').each( function(){
	$(this).minicolors({
		animationSpeed: 50,
		animationEasing: 'swing',
		change: null,
		changeDelay: 0,
		control: 'hue',
		dataUris: true,
		defaultValue: '',
		format: 'rgb',
		hide: null,
		hideSpeed: 100,
		inline: false,
		keywords: '',
		letterCase: 'lowercase',
		opacity: true,
		position: 'top	right',
		show: null,
		showSpeed: 100,
		theme: 'default'
	})
});	
```

**Comment by claviska** [comment]
Can you confirm you're using the latest version? The RGBA demo in the example doesn't seem to do that.

Do you experience the same thing with a minimal example? You might be overwriting settings or something and it would be really helpful if you could verify this :)

**Comment by claviska** [comment]
Closing since I can't replicate and no feedback has been provided.
