### ISSUE TITLE
Feature Request: Eye Dropper

### ISSUE THREAD

**Issue by shaneparsons** [claviska/jquery-minicolors#202]
It likely won't be easy to pull off, but integrating an Eye Dropper would be amazing.

**Comment by claviska** [comment]
Alas, there's no guaranteed way to do this except for images/canvas elements: http://stackoverflow.com/questions/1936021/javascript-eyedropper-tell-color-of-pixel-under-mouse-cursor

**Comment by shaneparsons** [comment]
Ah okay. I had a feeling there was a good reason for it not already being part of minicolors.
I appreciate the quick response!
