### ISSUE TITLE
Issue (with fix) with null settings object

### ISSUE THREAD

**Issue by bvossler** [claviska/jquery-minicolors#204]
When using jquery-minicolors in an Angular wrapper there are times when the settings object is null when the field is being destroyed. I simply add the following code directly after line # 602 and it fixes this issue. Can you include this or something similar in subsequent releases so others don;t have this issue? It would also be nice for me not to have to remember to add this on every update.

`if (settings == null) return;`

Thank you

**Comment by claviska** [comment]
Make sure you're calling destroy on minicolors before destroying the input. The suggested workaround circumvents the error but may have other side effects. We need to find out why `settings` is `null` before we add arbitrary code into the mix.

**Comment by claviska** [comment]
Closing to due to age and no reply. If this is still an issue, please post a reduced example so we can replicate this behavior.
