### ISSUE TITLE
Using pre-defined Swatches with 'bottom right'-position leads to cropped / partial visible first swatch with default theme

### ISSUE THREAD

**Issue by MarkusTiede** [claviska/jquery-minicolors#208]
Using all (7) pre-defined Swatches with 'bottom right'-position leads to cropped / partial visible first swatch using the default theme:

![jquery-minicolors-issue](https://cloud.githubusercontent.com/assets/1764012/17479237/967c48fc-5d71-11e6-98b3-9f269e3665ab.png)

Thanks in advance and with best regards,

MarkusT

**Comment by claviska** [comment]
Thanks, fixed the conflicting selector that caused this.
