### ISSUE TITLE
Increase the size of the colorpicker

### ISSUE THREAD

**Issue by abhishek-kanungo** [claviska/jquery-minicolors#210]
Hi.Thanks for this awesome plugin but I would like to increase the overall size of the picker. Coudn't find any options for this.

**Comment by claviska** [comment]
It's called minicolors because it's the smallest possible control you can have while allowing selection of any color with a palette. There are no plans to change that at this time.

**Comment by abhishek-kanungo** [comment]
Ok.Thanks for the lightening response.My designer has modified the image and the css and its seems to be working fine for the time-being :)
