### ISSUE TITLE
About npm version

### ISSUE THREAD

**Issue by x09326** [claviska/jquery-minicolors#211]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

I found that this proj on [npm](https://www.npmjs.com/package/jquery-minicolors) is not the latest version.
Hope you can update it.
If you update it, I can use npm auto-update to download your latest version from then on.
Thanks!
https://github.com/cdnjs/cdnjs/pull/9079#issuecomment-249407138

**Comment by claviska** [comment]
Per the readme, somebody else created that repo and is unresponsive. The official NPM repo is located here:

https://www.npmjs.com/package/@claviska/jquery-minicolors

**Comment by x09326** [comment]
Thanks!
