### ISSUE TITLE
About version 2.1.8

### ISSUE THREAD

**Issue by x09326** [claviska/jquery-minicolors#212]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I found there are ```jquery.minicolors-min.js``` and ```jquery.minicolors.min.js``` in the versios 2.1.8.
Is this version valid?
Thanks!
https://github.com/cdnjs/cdnjs/pull/9079

**Comment by markvantilburg** [comment]
see https://github.com/claviska/jquery-minicolors/issues/150 should be .min.js
