### ISSUE TITLE
Add show and hide methods

### ISSUE THREAD

**Issue by abhi06991** [claviska/jquery-minicolors#213]
Everything is working perfectly. I just need to hide the colorbox on checking a condition , whether a particular div is visible or hidden.

Is there any method to achive this?

**Comment by claviska** [comment]
There's no [method](http://labs.abeautifulsite.net/jquery-minicolors/#methods) for that at the moment. Open to PRs.

**Comment by claviska** [comment]
See #235

**Comment by pjfsilva** [comment]
This seems it never got to https://labs.abeautifulsite.net/jquery-minicolors/#methods ?  It still doesn't list hide/show as methods.

**Comment by claviska** [comment]
Good catch, updated.
