### ISSUE TITLE
Add option for custom class names

### ISSUE THREAD

**Issue by stephanrauh** [claviska/jquery-minicolors#214]
I'd like to be able to add a custom CSS inline style or CSS class to the colorpicker widget. Something like 

```JavaScript
$(function() {$('#input_j_idt6\\:j_idt11').minicolors({ 
    style: "margin-top:10px",
    class: "my-favorite-css-class", 
    theme: 'bootstrap' });
});
```

**Comment by claviska** [comment]
I'll entertain a PR for a custom class that gets attached to the main container, but I'm not fond of inline styles or passing them in a config, especially as a string.

**Comment by stephanrauh** [comment]
I see. I can't promise I'll find enough spare time to send you a PR adding the class anytime soon, but I'll put it on my long list of things to do :). 

BTW, the source of the feature request is the BootsFaces project. We use your ColorPicker, and we're very happy with it. Keep on the good work!

**Comment by claviska** [comment]
If there's still interest in a custom class name, feel free to open a PR.
