### ISSUE TITLE
Allow more than seven swatch colors at a time

### ISSUE THREAD

**Issue by FrancoisClaudios** [claviska/jquery-minicolors#215]
Hi, this plugin is great. I am using it in one of our project. I have one suggestion, can you please add color pallete option to display color pallete more than the default 7 colors? For that it would be easy  for the users to choose colors by selecting a pallete.  Right now I manipulated the script and displayed the pallete only like below: It would be cool if many colors can be placed in here. Thanks man!

![colorpallete](https://cloud.githubusercontent.com/assets/23493517/20512136/609cd82e-b0b8-11e6-904d-b8ddfb86b2ae.PNG)

**Comment by claviska** [comment]
I'm open to a PR that removes the seven color limit. I believe it was added because the height of the swatches isn't automatic, but shouldn't be too difficult to update.

**Comment by FrancoisClaudios** [comment]
For now I commented out the` if() statement` that handles seven limited swatches. Yes, exactly I have issue on the swatches height. Can we make it automatic? It would be great for all I think. Thanks man!

**Comment by claide** [comment]
Hi, I managed to do this by editing the core script. I hope this will be helpful for all the plugin users. So this is how I did it:

1.  Add the `swatches` in properties and fill in the desired colors like below.

`swatches: [
                            "#000000","#444444","#666666","#999999","#cccccc","#eeeeee","#f3f3f3","#ffffff",
                            "#f00","#f90","#ff0","#0f0","#0ff","#00f","#90f","#f0f",
                            "#f4cccc","#fce5cd","#fff2cc","#d9ead3","#d0e0e3","#cfe2f3","#d9d2e9","#ead1dc",
                            "#ea9999","#f9cb9c","#ffe599","#b6d7a8","#a2c4c9","#9fc5e8","#b4a7d6","#d5a6bd",
                            "#e06666","#f6b26b","#ffd966","#93c47d","#76a5af","#6fa8dc","#8e7cc3","#c27ba0",
                            "#c00","#e69138","#f1c232","#6aa84f","#45818e","#3d85c6","#674ea7","#a64d79",
                            "#900","#b45f06","#bf9000","#38761d","#134f5c","#0b5394","#351c75","#741b47",
                            "#600","#783f04","#7f6000","#274e13","#0c343d","#073763","#20124d","#4c1130"
                          ]`

2. In your `jquery.minicolors.js`, find `//swatches` and replace it by the code below:


`if (settings.swatches && settings.swatches.length !== 0) {
            //Remove color grid and slider
            $( ".minicolors-grid" ).remove(); 
            $( ".minicolors-slider" ).remove();
            panel.addClass('minicolors-with-swatches');
            panel.addClass('clear');
            swatches = $('<ul class="minicolors-swatches"></ul>')
                .appendTo(panel);
                $( ".minicolors-swatches" ).css({
                    'top':'5px',
                    'position':'relative'
                });
                $( ".minicolors-panel" ).css({
                    'height':'auto',
                    'background':'#222222'
                });
            for(i = 0; i < settings.swatches.length; ++i) {
                swatch = settings.swatches[i];
                swatch = isRgb(swatch) ? parseRgb(swatch, true) : hex2rgb(parseHex(swatch, true));
                $('<li class="minicolors-swatch minicolors-sprite"><span class="minicolors-swatch-color"></span></li>')
                    .appendTo(swatches)
                    .data('swatch-color', settings.swatches[i])
                    .find('.minicolors-swatch-color')
                    .css({
                        backgroundColor: rgb2hex(swatch),
                        opacity: swatch.a
                    });
                settings.swatches[i] = swatch;
            }
        }`

Happy coding 👍

**Comment by FrancoisClaudios** [comment]
@claide , Thanks man!
