### ISSUE TITLE
Remove data URIs per #156

### ISSUE THREAD

**Issue by claviska** [claviska/jquery-minicolors#217]
Data URIs add bloat to the library, and a proper build task will prevent relative linking issues that they were introduced to combat. (This responsibility should be on the projects using the library, not the library itself.)

See #156 for more details.

**Comment by claviska** [comment]
Removed in dc2ffe817ac3f89abbe4873104030fe774355512

**Comment by ehrig** [comment]
You might want to mention this change on http://labs.abeautifulsite.net/jquery-minicolors/ as well.

**Comment by claviska** [comment]
Updated, thanks!
