### ISSUE TITLE
Settings via data- attributes

### ISSUE THREAD

**Issue by medhi** [claviska/jquery-minicolors#221]
I would like to set some settings via `data-` attributes, particularly `swatches`, is that possible?

**Comment by claviska** [comment]
The plugin doesn't support Bootstrap-style data attribute initialization (except for `data-opacity`), but you can do something like this:

```js
// Loop through each control
$('.your-selector').each(function() {
  
  // Initialize each control using data attributes
  $(this).minicolors({
    prop1: $(this).attr('data-prop1'),
    prop2: $(this).attr('data-prop2'),
    ...
  });
});

```
