### ISSUE TITLE
how to work with meteor?

### ISSUE THREAD

**Issue by Nemra1** [claviska/jquery-minicolors#222]
im working in rocket chat app
and i need to add font text colors for users like this
![ilv50](https://cloud.githubusercontent.com/assets/22897987/25017443/1f9659ea-2084-11e7-87ed-e55bcea5c136.jpg)
this standard explain ..
i like to used jquery-minicolors to apply the users to text with font colors

**Comment by claviska** [comment]
Please ask this question on StackOverflow. Trying to keep the issue tracker to bugs and feature requests only. Thanks!
