### ISSUE TITLE
Update npm package to v2.2.4

### ISSUE THREAD

**Issue by C-Lodder** [claviska/jquery-minicolors#225]
The [npm site](https://www.npmjs.com/package/jquery-minicolors) is still showing v2.1.10 as the latest version and needs to be updated to v2.2.4

Would you mind doing this please?

**Comment by claviska** [comment]
That's not the official module — somebody else published it. The official is namespaced and up to date: https://www.npmjs.com/package/@claviska/jquery-minicolors

**Comment by C-Lodder** [comment]
ah thanks for clarifying
