### ISSUE TITLE
null checked as a string in data in value setter

### ISSUE THREAD

**Issue by derklempner** [claviska/jquery-minicolors#233]
Minicolors is great, thanks.  One thing I noticed on line 113:

```if(typeof(data) === 'object' && data !== 'null') {```

I think the idea was to check for actual null here?

**Comment by claviska** [comment]
That second condition is dead since `data` will never be an object _and_ a string. It can be safely removed if you want to submit a PR :)

**Comment by derklempner** [comment]
The niggle is when ``data`` is actually ``null`` for some reason - our good friend javascript considers ``typeof(null)==='object'; // true`` .  So it passes the condition, but then reading properties like ``data.opacity`` etc are on null, so it will complain.  Will submit a PR.
