### ISSUE TITLE
Mouse-up not triggering when loading via ui-sref (angular)

### ISSUE THREAD

**Issue by neel-pu** [claviska/jquery-minicolors#238]
I'm loading a page via ui-sref in angular with a colorpicker. Every time I load that page and click on the color picker, the mouse doesn't register the mouse-up event, which has me stuck with an infinitely dragging pointer even though I already let go of the mouse. This happens when I click the grid, the slider, or the opacity-slider. But when I hard-refresh the page and don't load it via angular routes(ui-sref), the colorpicker works fine. Is there something I missed during initialization?

**Comment by claviska** [comment]
Sorry nobody got to this. I don't have any experience with Angular, so I don't have any insights for you. If this is still an issue, feel free to post a minimal example and I'll reopen.
