### ISSUE TITLE
'value' method does not accept opacity = 0

### ISSUE THREAD

**Issue by jgasiorowski** [claviska/jquery-minicolors#248]
https://github.com/claviska/jquery-minicolors/blob/ee633a109f4484b76403762b776333b909bc1446/jquery.minicolors.js#L114

Beacuse of that `if` statement is not checking for `undefined` when you pass `{ color: '#aaaaaa', opacity: 0}` to `'value'` method then the opacity setting gets ignored

**Comment by claviska** [comment]
Nice catch. Care to submit a PR?

**Comment by jgasiorowski** [comment]
submitted. Sorry if I done something wrong. (My first PR to public project)

**Comment by jgasiorowski** [comment]
@claviska is everything fine with that PR? champagne is waiting for celebration :)

**Comment by claviska** [comment]
Yes, sorry about that!
