### ISSUE TITLE
Reason for using event.keyCode instead of event.which?

### ISSUE THREAD

**Issue by onassar** [claviska/jquery-minicolors#252]
In `v2.3.0` on line `1091` I notice you're running a switch on `event.keyCode`. I'm wondering if there's a specific reason for doing so. From what I understand, `event.which` should be used, because some browsers don't support `event.keyCode` (which I've seen in production from time to time).

Is there a specific reason, or can I change that safely?

References:
https://stackoverflow.com/questions/4471582/keycode-vs-which
http://unixpapa.com/js/key.html

**Comment by claviska** [comment]
Apparently things are changing. Looks like [event.which is also deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) though.

Maybe [event.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) is the best choice here? It’s more readable and seems to have great browser support.

Thoughts?

**Comment by onassar** [comment]
It looks like the jQuery event doesn't support `key`, rather just `which` and `keyCode` (in some cases).

**Comment by claviska** [comment]
It uses the original event, so as long as the client supports it then `event.key` will work.

Example: https://jsfiddle.net/2payzh75/

**Comment by onassar** [comment]
Ahh okay I see. Well you're running your `switch/case` against the `keyCode` and it's respective numbers, so you'd then need to change the values you're "casing" against. I think switching over to `event.which` is the least likely to cause a breaking change for existing users, but it's your call :-P

**Comment by onassar** [comment]
See here as well: https://caniuse.com/#feat=keyboardevent-key

**Comment by claviska** [comment]
Yay, IE/Edge! 🎉 

Since this is a jQuery plugin, I'm cool with `event.which` since it's normalized and officially supported by jQuery. It's probably the safer bet for now.

Thanks :)

**Comment by onassar** [comment]
Lol. Any chance of you putting out `v2.3.1`? I have a thing for only using official releases and never modifying the underlying repo ;)

**Comment by claviska** [comment]
Sure, submit a PR and it will land in the next version.

Is this breaking in a browser that you're noticing right now, or is this just a wanted change?

**Comment by onassar** [comment]
I use Sentry for production logging and have noticed a bunch of related bugs with other parts of my app whereby `event.keyCode` is not available. So I just went through changing it all over the place (since it's effectively wrong given cross-browser issues). I'm guessing we have some users who have run into this, just hasn't been explicitly reported.

K I'll do a quick PR now.

**Comment by claviska** [comment]
Fixed in #253

**Comment by onassar** [comment]
Thanks for jumping on this so quick.
Also fyi this is how we styled minicolors :)
![](https://i.imgur.com/BT0kOd1.png)

**Comment by claviska** [comment]
np — that looks great btw!

**Comment by onassar** [comment]
:)
