### ISSUE TITLE
Will this work with bootstrap 4?

### ISSUE THREAD

**Issue by RaleighGit** [claviska/jquery-minicolors#254]
I have played around with getting this to work with bootstrap 4 with no luck.  I am wondering if anybody else has been successful or not.

**Comment by claviska** [comment]
I believe so. What's not working for you? Some sample code and an image would help identify if it's a problem with minicolors or your implementation.

**Comment by claviska** [comment]
Closing due to no response. Please post additional info if this is still an issue for you.
