### ISSUE TITLE
Minicolors inside a jQueryUI Dialog

### ISSUE THREAD

**Issue by dioobr** [claviska/jquery-minicolors#260]
![screen shot 2018-09-21 at 18 01 58](https://user-images.githubusercontent.com/16680429/45905894-7f33a500-bdc8-11e8-9851-d03d35306383.png)

Hi, as you can see, the colorpicker is created inside the dialog, and if the dialog there's a small width or height, part of the colorpicker doesn't show. Any suggestions to solve it?

**Comment by claviska** [comment]
Closing due to no response. Please post additional info if this is still an issue.
