### ISSUE TITLE
Panel doesn't show with jQuery Slim

### ISSUE THREAD

**Issue by kdeclerck** [claviska/jquery-minicolors#267]
Recently support for jQuery Slim has been added with https://github.com/claviska/jquery-minicolors/pull/258. 

The panel initially has a `display: none` css rule. The `panel.css('opacity', 0)` doesn't remove this rule so the panel doesn't show.

**Comment by claviska** [comment]
Good catch!

**Comment by claviska** [comment]
Done.

**Comment by AdriVanHoudt** [comment]
@claviska Thanks for releasing this! 🎉 
I think you did forget to update the .min.js file though. Could you do a release with the updated file? I'll see if I can do a PR for this.

**Comment by AdriVanHoudt** [comment]
@claviska I did a PR for this over here: https://github.com/claviska/jquery-minicolors/pull/269
