### ISSUE TITLE
Position failed

### ISSUE THREAD

**Issue by 4URGB** [claviska/jquery-minicolors#270]
Hi,

first of all - great script!

I trie to work with it, but setting the position to another value failed.

```html
<input data-position="bottom left" ...> - wont work
```
by ini the minicolors

```js
position: $(this).attr('data-position') || 'bottom right',  - wont work too
```

Also i use 

```js
format: $(this).attr('data-format') || 'rgba',
```

and 

```html
<input data-format="rgba" ...>
```

but i received a hex value in the input field!?

It always display the left bottom classes.

What i do wrong?

**Comment by claviska** [comment]
Config via data attributes are not supported by minicolors unless you initialize it with them as in the demo:

https://github.com/claviska/jquery-minicolors/blob/master/index.html#L69-L77
