### ISSUE TITLE
Initial selection is black

### ISSUE THREAD

**Issue by caudex-mbruce** [claviska/jquery-minicolors#288]
I have installed using npm (npm i @claviska/jquery-minicolors) and imported js in app.js but there seems to be a bug when you first click on the colour pallette, no matter where you click, the initial colour is black. Clicking a 2nd time will then select the correct colour.

**Comment by claviska** [comment]
As is, I cannot reproduce this and nobody else has reported this, so I suspect the problem is with your integration. If you can post a minimal test case so I can reproduce it, I'll be happy to take a look.
