### ISSUE TITLE
Worst documentation I've even seen !

### ISSUE THREAD

**Issue by biggestdickus** [claviska/jquery-minicolors#295]
Are you trying to impress someone with your examples setup during a loop? Try adding real code examples beside each example in your documentation.
How the hell do I get the rgbaString ?? Is the method the name or 'method' name being passed? Is the data 'rgbaString'  put into an array [] ?????  Most people would go to another color picker rather to spend hours trying to figure out how your's works.

$(rgba).minicolors('method', [data]);
$(rgba).minicolors('rgbaString', [data]); ?
$(rgba).minicolors('method', [rgbaString]); ??
$(rgba).minicolors('method', rgbString()); ???

alert('insert the code here') // return rgbString ???????????????????????

The following is how the rest of world shows how to use options:
```
var arr=['#ff0000','#00ff00','#0000ff']
  $(rgba).minicolors({
    control: 'hue',
    position: 'bottom left',
    letterCase: 'lowercase',
    opacity: true,
    defaultValue: '#ff0000',
    swatches: arr
  });
```

**Comment by claviska** [comment]
The project's been around for close to a decade and you're the only one who can't seem to figure it out. I was reluctant to reply given the tone of your message, but I'll be the bigger person here.

```js
$('input').minicolors('rgbaString')
```
