### ISSUE TITLE
Duplicated values in the swatch result in multiple same colors in the swatch

### ISSUE THREAD

**Issue by markvantilburg** [claviska/jquery-minicolors#305]
`<input type="text" id="swatches" class="demo" data-swatches="#ef9a9a|#ef9a9a|#ef9a9a|#ef9a9a|#90caf9|#a5d6a7|#fff59d|#ffcc80|#bcaaa4|#eeeeee|#f44336|#2196f3|#4caf50|#ffeb3b|#ff9800|#795548|#9e9e9e" value="#f00">`

![Screenshot 2024-06-20 093635](https://github.com/claviska/jquery-minicolors/assets/4510245/6b945d98-f884-4ca7-b288-c6b8258be231)

**Comment by claviska** [comment]
Thanks for the PR, but I have the [same comment as here:](https://github.com/shoelace-style/shoelace/issues/2081#issuecomment-2180574156)

> Swatches are user-defined, so I don't think we want to change anything in the component. There may be use cases where a swatch _should_ be shown more than once. For example, the user might want the first two rows to be preset colors and another row to contain frequently used or "favorite" colors.
>
> By eliminating duplicates at the component level, we take away that option for them with no way to provide it back.
