### ISSUE TITLE
Reading & writing RGBA colors

### ISSUE THREAD

**Issue by rvision** [claviska/jquery-minicolors#75]
Any chance of setting the RGBA color? rgbString & rgbaString are only for getting a value if I understood correctly.

Nice looking plugin, btw :+1:

**Comment by JoomliC** [comment]
Hi all!

I have created a PR to allow rgba values input (and additionally, i have added the possibility to activate css color keywords (transparent, inherit, initial).
https://github.com/claviska/jquery-minicolors/pull/170

Testing and feedback welcome!
Cyril

**Comment by claviska** [comment]
See #170 for further discussion.
